global:
  sendAnonymousUsage: true

entryPoints:
  web:
    address: :80

accessLog:

api:
  insecure: true
  dashboard: true

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
    network: traefik-public
